name: Packer Status Check

on:
  pull_request:
    branches:
      - main  # Runs on PRs to the main branch

jobs:
  packer-format-validate:
    name: Packer Format & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: zip repository code
        run : zip -r webapp.zip .

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest  # Installs the latest version of Packer



      - name: Run Packer Format Check
        run: |
          if ! packer fmt -check .; then
            echo "Packer format check failed!"
            exit 1
          fi
          echo "Packer format check passed."

      - name: Run Packer Validate
        run: |
          if ! packer validate .; then
            echo " Packer validation failed!"
            exit 1
          fi
          echo " Packer validation passed."
