name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Integration Tests
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_ROOT_PASS: ${{secrets.DB_ROOT_PASS}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.13.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.13.1'

      - name: Install npm dependencies
        run: npm install

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          sudo systemctl enable mysql

      - name: Wait for MySQL to Start
        run: sleep 10  # Ensures MySQL service is fully running before creating the database

      # - name: Check MySQL Authentication Method
      #   run: sudo mysql -u root -e "SELECT user, host, plugin FROM mysql.user WHERE user='root';"

      - name: Set MySQL Root Password and Authentication
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '$DB_PASSWORD';"

      - name: Create Database and User If Not Exists
        run: |
          sudo mysql -u root -p"$DB_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;"
          sudo mysql -u root -p"$DB_PASSWORD" -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';"
          sudo mysql -u root -p"$DB_PASSWORD" -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';"
          sudo mysql -u root -p"$DB_PASSWORD" -e "FLUSH PRIVILEGES;"

      - name: Run Integration Tests
        run: npm run test







